FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip python-is-python3 && \
    apt-get clean clean

RUN pip install -U pip setuptools && pip install poetry

WORKDIR /apps/sunva-backend
ADD . /apps/sunva-backend
RUN poetry install
CMD poetry run uvicorn main:app --reload
